<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera [
    <!ELEMENT cartelera (pelicula)+>
    <!ELEMENT pelicula (titulo,titulo_original,nacionalidad,genero,(clasificacion | sin_clasificar),sinopsis,director,reparto,web,cartel)>
    <!ATTLIST pelicula codigo CDATA #REQUIRED>
    <!ATTLIST pelicula duracion CDATA #REQUIRED>
    <!ATTLIST pelicula anio CDATA #IMPLIED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT titulo_original (#PCDATA)?>
    <!ELEMENT nacionalidad (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
    <!ELEMENT clasificacion (#PCDATA)>
    <!ATTLIST clasificacion edad (tp|8|12|16|18) #REQUIRED>
    <!ELEMENT sin_clasificar EMPTY>
    <!ELEMENT sinopsis (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT reparto (actor)+>
    <!ELEMENT actor (#PCDATA)>
    <!ELEMENT web (#PCDATA)>
    <!ELEMENT cartel (#PCDATA)>


]>
<!-- titulo,titulo_original,nacionalidad,genero,(clasificacion | sin_clasificar),sinopsis,director,reparto,web,cartel -->
<cartelera>
  <pelicula codigo="p1" duracion="152" anio="2002">
    <titulo>AQUELLAS JUERGAS UNIVERSITARIAS</titulo>
    <titulo_original>Old School</titulo_original>
    <nacionalidad>Estados Unidos</nacionalidad>
    <genero>Comedia</genero>
    <clasificacion edad="tp" />
    <sinopsis>
      Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son exactamente lo que
      esperaban. Mitch tiene una novia ninfomana que se mete en la cama con el primero que agarra.
      Frank se ha casado y su matrimonio nada...
    </sinopsis>
    <director>Todd Philips</director>
    <reparto>
      <actor>Luke Wilson</actor>
      <actor>Will Farrel</actor>
      <actor>Vince Vaughn</actor>
    </reparto>
    <web>http://www.uip.es</web>
    <cartel>caratulas/Aquellas juergas.jpg</cartel>
  </pelicula>
  <pelicula codigo="p17" duracion="06">
    <titulo>EL ORO DE MOSCÚ</titulo>
    <nacionalidad>España</nacionalidad>
    <genero>Comedia</genero>
    <sin_clasificar />
    <sinopsis>
      Por una extraña coincidencia del destino, alguien recibe una informacion extraconfidencial de
      un anciano en sus últimos segundos de vida: el secreto mejor guardado de la Historia. El
      receptor, un trabajador de hospital, se lo comunica secretamente a un supuesto amigo. ...
    </sinopsis>
    <director>Jesús Bonilla</director>
    <reparto>
      <actor>Jesús Bonilla</actor>
      <actor>Santiago Segura</actor>
      <actor>Alfredo Landa</actor>
      <actor>Concha Velasco</actor>
      <actor>Antonio Resines</actor>
      <actor>Gabino Diego, Maria Barranco</actor>
      <actor>Maria Barranco</actor>
    </reparto>
  </pelicula>
</cartelera>